// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to summarize a movie trailer and provide a brief overview of the plot.
 *
 * - summarizeTrailer - A function that handles the trailer summarization process.
 * - SummarizeTrailerInput - The input type for the summarizeTrailer function.
 * - SummarizeTrailerOutput - The return type for the summarizeTrailer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeTrailerInputSchema = z.object({
  trailerUrl: z
    .string()
    .describe('The URL of the movie trailer to summarize.'),
});
export type SummarizeTrailerInput = z.infer<typeof SummarizeTrailerInputSchema>;

const SummarizeTrailerOutputSchema = z.object({
  summary: z
    .string()
    .describe('A brief summary of the movie trailer, highlighting key plot points.'),
});
export type SummarizeTrailerOutput = z.infer<typeof SummarizeTrailerOutputSchema>;

export async function summarizeTrailer(input: SummarizeTrailerInput): Promise<SummarizeTrailerOutput> {
  return summarizeTrailerFlow(input);
}

const summarizeTrailerPrompt = ai.definePrompt({
  name: 'summarizeTrailerPrompt',
  input: {schema: SummarizeTrailerInputSchema},
  output: {schema: SummarizeTrailerOutputSchema},
  prompt: `You are a movie expert. Please provide a brief summary of the movie based on the following trailer URL, highlighting key plot points:

Trailer URL: {{{trailerUrl}}}

Summary:`, // Just ask it to give a summary directly
});

const summarizeTrailerFlow = ai.defineFlow(
  {
    name: 'summarizeTrailerFlow',
    inputSchema: SummarizeTrailerInputSchema,
    outputSchema: SummarizeTrailerOutputSchema,
  },
  async input => {
    const {output} = await summarizeTrailerPrompt(input);
    return output!;
  }
);
